create OR REPLACE view AD_VBHPSA as
SELECT
    PED.ORDEMCARGA,
    ITE.SEQUENCIA,
    CAB.NUNOTAPR,
    CAB.PREORDEM,
    NVL(PED.SEQCARGA,CAB.SEQCARGA) SEQCARGA,
    PRO.CODPROD,
    ITE.QTDNEG,
    ITE.CODVOL,
    NVL(CAB.RECEBECX,'N') RECEBECX,
    NVL(CAB.OBSERVACAO,' ') OBSERVACAO,
    CAB.CODTIPOPER,
    CAB.DTPREV,
    CAB.CODPARC,
    CAB.STATUSLOG,
    CAB.MOTORISTA,
    (SELECT DESCROPER FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER AND DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP TOP WHERE TOP.CODTIPOPER = CAB.CODTIPOPER)) DESCROPER,
    CAB.CODPARCORIG,
    CAB.DTRETORNO
FROM AD_TBHCAB CAB
         INNER JOIN AD_TBHITE ITE ON ITE.NUNOTAPR = CAB.NUNOTAPR AND NVL(ITE.QTDNEG,0) != 0
         INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
         INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
         LEFT JOIN TGFVOA VOA ON VOA.CODVOL = CASE WHEN PAR.AD_RECEBECX = 'S'
                                                       THEN 'CX'
                                                   ELSE ITE.CODVOL END
    AND VOA.CODPROD = ITE.CODPROD
         LEFT JOIN TGFCAB PED ON PED.NUNOTA = CAB.NUNOTA
